services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - /var/lib/jellyfin:/config
      - /media/myfiles:/media
    environment:
      - TZ=Asia/Jerusalem

  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /media/myfiles:/share
    environment:
      - USER=tomer;9995363
      - SHARE=myfiles;/share;yes;no;no;tomer
    command: '-g "map to guest = never"'

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - uptime_kuma_data:/app/data

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - qbittorrent_config:/config
      - /media/myfiles/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
      - WEBUI_PORT=8080

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    volumes:
      - prowlarr_config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - radarr_config:/config
      - /media/myfiles/movies:/movies
      - /media/myfiles/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - sonarr_config:/config
      - /media/myfiles/shows:/shows
      - /media/myfiles/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem

volumes:
  uptime_kuma_data:
  qbittorrent_config:
  prowlarr_config:
  radarr_config:
  sonarr_config:
